export const LOAD_CERTIFICATES = 'LOAD_CERTIFICATES';
export const SET_TOTAL_NUMBER_ITEMS = 'SET_TOTAL_NUMBER_ITEMS';
export const CHANGE_PAGE = 'CHANGE_PAGE';
export const CHANGE_SIZE = 'CHANGE_SIZE';
export const DELETE_CERTIFICATE = 'DELETE_CERTIFICATE';
export const SET_AUTH = 'SET_AUTH';
export const SET_ADMIN = 'SET_ADMIN';
export const SET_EMAIL_ACTION = 'SET_EMAIL_ACTION';

