export const LOAD_CERTIFICATES = 'LOAD_CERTIFICATES';
export const SET_TOTAL_NUMBER_ITEMS = 'SET_TOTAL_NUMBER_ITEMS';
export const CHANGE_PAGE = 'CHANGE_PAGE';
export const CHANGE_SIZE = 'CHANGE_SIZE';
export const CREATE_CERTIFICATE = 'CREATE_CERTIFICATE';
export const EDIT_CERTIFICATE = 'EDIT_CERTIFICATE';
export const DELETE_CERTIFICATE = 'DELETE_CERTIFICATE';